%% ============================================================
% LINEAR MIXED-EFFECTS MODEL
%
% RESEARCH QUESTION:
%
% Does auditory condition predict reaction time
% AFTER controlling for presentation order?
%
% OUTCOME VARIABLE:
% Standardized Reaction Time (Z_RT)
%
% PREDICTORS:
% 1. Auditory Condition:
%       Silence
%       Slow
%       Fast
%
% 2. Presentation Round:
%       Round 1
%       Round 2
%       Round 3
%
% MODEL:
%
% Z_RT ~ Condition + Round + (1 | Subject)
%
% INTERPRETATION:
%
% The Condition effect tells us whether auditory condition
% is associated with reaction time when presentation order
% is statistically held constant.
%
% The Round effect tells us whether response time changes
% between the first, second, and third rounds,
% independently of auditory condition.
%
% STANDARDIZATION:
%
% For EACH participant separately:
%
% 1. Take all valid RT trials from all 3 conditions together
% 2. Convert the complete valid RT list to Z-scores
% 3. Keep each individual trial as one observation
%
% IMPORTANT:
%
% REMOVE_OUTLIERS = false;
%
% means:
% Subjects 6 and 8 are removed for consistency
% with the main inferential RT analyses.
%
% Change to false to keep all participants.
%% ============================================================

clear;
clc;
close all;


%% ============================================================
% SETTINGS
%% ============================================================

REMOVE_OUTLIERS = true;


%% ============================================================
% 1. CHOOSE PARTICIPANT FOLDER
%% ============================================================

path = uigetdir( ...
    pwd, ...
    'Choose the folder containing participant files');


if isequal(path, 0)

    error('No folder was selected.');

end


fprintf('\nSelected folder:\n%s\n', ...
    path);


%% ============================================================
% 2. FIND PARTICIPANT FILES
%% ============================================================

xlsx_files = ...
    dir(fullfile(path, '*exel sub*.xlsx'));

xls_files = ...
    dir(fullfile(path, '*exel sub*.xls'));

csv_files = ...
    dir(fullfile(path, '*exel sub*.csv'));


all_files = [ ...
    xlsx_files; ...
    xls_files; ...
    csv_files];


files = ...
    {all_files.name};


n_subjects_original = ...
    length(files);


fprintf('\nFound %d participant files:\n', ...
    n_subjects_original);


disp(files');


if n_subjects_original < 2

    error('MATLAB found fewer than 2 participant files.');

end


%% ============================================================
% 3. PREPARE ONE LARGE TRIAL-LEVEL DATASET
%% ============================================================

all_subjects = ...
    strings(0,1);


all_RT_new = ...
    zeros(0,1);


all_conditions = ...
    strings(0,1);


all_round_numbers = ...
    zeros(0,1);
%% Prepare subject-level outlier information

subject_names_for_outlier_check = ...
    strings(0,1);

subject_mean_logRT_for_outlier_check = ...
    zeros(0,1);

%% ============================================================
% 4. ANALYZE EACH PARTICIPANT
%% ============================================================

for s = 1:n_subjects_original


    filename = ...
        fullfile(path, files{s});


    %% Read file

    T = readtable( ...
        filename, ...
        'VariableNamingRule', ...
        'preserve');


    %% Participant name

    [~, name, ~] = ...
        fileparts(files{s});


    current_subject = ...
        string(name);


    %% --------------------------------------------------------
    % READ VARIABLES
    %% --------------------------------------------------------

    % Column B = auditory condition

    auditory_condition = ...
        lower(strtrim(string(T{:,2})));


    % Column F = action/status

    action_status = ...
        str2double(string(T{:,6}));


    % Column G = reaction time

    RT_ms = ...
        str2double(string(T{:,7}));


    % Column H = error

    errors = ...
        str2double(string(T{:,8}));


    %% ========================================================
    % 4A. DETERMINE PRESENTATION ORDER
    %
    % The code finds which condition appeared first,
    % second, and third in this participant's file.
    %% ========================================================

    condition_names = [ ...
        "silence"; ...
        "slow"; ...
        "fast"];


    first_occurrence = ...
        NaN(3,1);


    for c = 1:3


        first_row = ...
            find( ...
            auditory_condition == condition_names(c), ...
            1, ...
            'first');


        if ~isempty(first_row)

            first_occurrence(c) = ...
                first_row;

        end


    end


    %% Check that all 3 conditions exist

    if any(isnan(first_occurrence))

        warning( ...
            '%s does not contain all 3 conditions.', ...
            files{s});

        continue;

    end


    %% Sort conditions by their first appearance

    [~, presentation_order] = ...
        sort(first_occurrence);


    %% Create mapping:
    %
    % condition_round(c) tells us whether
    % condition c was presented in Round 1, 2, or 3.

    condition_round = ...
        NaN(3,1);


    for round_number = 1:3

        condition_index = ...
            presentation_order(round_number);


        condition_round(condition_index) = ...
            round_number;

    end


    %% Create round number for every row

    round_number_per_trial = ...
        NaN(height(T),1);


    for c = 1:3

        round_number_per_trial( ...
            auditory_condition == condition_names(c)) = ...
            condition_round(c);

    end


    %% Print participant order

    fprintf('\n%s\n', ...
        current_subject);


    fprintf( ...
        'Round 1 = %s\n', ...
        condition_names( ...
        presentation_order(1)));


    fprintf( ...
        'Round 2 = %s\n', ...
        condition_names( ...
        presentation_order(2)));


    fprintf( ...
        'Round 3 = %s\n', ...
        condition_names( ...
        presentation_order(3)));


    %% ========================================================
    % 4B. VALID RT TRIALS
    %% ========================================================

    valid_trials = ...
        action_status == 1 & ...
        errors == 0 & ...
        RT_ms < 4000 & ...
        ~isnan(RT_ms) & ...
        ~isnan(round_number_per_trial);


    %% All valid RTs for this participant

all_valid_RT = ...
    RT_ms(valid_trials);


%% Check that participant has enough valid trials

if numel(all_valid_RT) < 2 || ...
        std(all_valid_RT, 'omitnan') == 0

    warning( ...
        '%s does not have enough valid RT variability.', ...
        files{s});

    continue;

end


%% ========================================================
% 4C. LOG TRANSFORM RT AND REMOVE TRIAL-LEVEL OUTLIERS
%
% For the linear mixed-effects model, we do NOT use Z-scores.
% We use original RT values in milliseconds, apply log,
% and remove trial-level outliers within each participant.
%
% Outlier criterion:
% More than 2 standard deviations from the participant's
% mean log RT.
%% ========================================================

RT_new_all = ...
    log(all_valid_RT);

mean_log_RT = ...
    mean(RT_new_all, 'omitnan');

std_log_RT = ...
    std(RT_new_all, 'omitnan');

log_RT_outlier = ...
    abs(RT_new_all - mean_log_RT) > 2 * std_log_RT;

RT_new = ...
    RT_new_all(~log_RT_outlier);
%% Save participant mean log RT for subject-level outlier check

subject_names_for_outlier_check = [ ...
    subject_names_for_outlier_check; ...
    current_subject];

subject_mean_logRT_for_outlier_check = [ ...
    subject_mean_logRT_for_outlier_check; ...
    mean(RT_new, 'omitnan')];

%% Get condition and order for valid observations

valid_conditions_all = ...
    auditory_condition(valid_trials);

valid_rounds_all = ...
    round_number_per_trial(valid_trials);

valid_conditions = ...
    valid_conditions_all(~log_RT_outlier);

valid_rounds = ...
    valid_rounds_all(~log_RT_outlier);


%% Subject ID repeated for every valid trial

valid_subjects = ...
    repmat( ...
    current_subject, ...
    numel(RT_new), ...
    1);
    %% ========================================================

    all_subjects = [ ...
        all_subjects; ...
        valid_subjects];

    all_RT_new = [ ...
        all_RT_new; ...
        RT_new];

    all_conditions = [ ...
        all_conditions; ...
        valid_conditions];


    all_round_numbers = [ ...
        all_round_numbers; ...
        valid_rounds];


end


%% ============================================================
% 5. CREATE TRIAL-LEVEL TABLE
%% ============================================================

model_data = table( ...
    all_subjects, ...
    all_RT_new, ...
    all_conditions, ...
    all_round_numbers);

model_data.Properties.VariableNames = { ...
    'Subject', ...
    'RT_new', ...
    'Condition_String', ...
    'Round_Number'};


%% ============================================================
% 6. AUTOMATIC SUBJECT-LEVEL OUTLIER REMOVAL
%
% This checks whether a participant's mean log RT is more than
% 2 standard deviations from the group mean.
%
% If REMOVE_OUTLIERS = true:
% Participants identified as subject-level outliers are removed.
%
% If REMOVE_OUTLIERS = false:
% No participants are removed.
%% ============================================================

if REMOVE_OUTLIERS

    group_mean_logRT = ...
        mean(subject_mean_logRT_for_outlier_check, 'omitnan');

    group_std_logRT = ...
        std(subject_mean_logRT_for_outlier_check, 'omitnan');

    subject_level_outlier = ...
        abs(subject_mean_logRT_for_outlier_check - group_mean_logRT) > ...
        2 * group_std_logRT;

    subjects_to_remove = ...
        subject_names_for_outlier_check(subject_level_outlier);

    remove_trial = ...
        ismember( ...
        lower(strtrim(model_data.Subject)), ...
        lower(strtrim(subjects_to_remove)));

    fprintf('\n================================================\n');
    fprintf('AUTOMATIC SUBJECT-LEVEL OUTLIER CHECK\n');
    fprintf('================================================\n');

    fprintf('\nGroup mean log RT = %.4f\n', group_mean_logRT);
    fprintf('Group SD log RT = %.4f\n', group_std_logRT);

    fprintf('\nSubjects identified as outliers:\n');

    if isempty(subjects_to_remove)

        fprintf('None\n');

    else

        disp(subjects_to_remove);

    end

    model_data(remove_trial,:) = [];

else

    fprintf('\n================================================\n');
    fprintf('NO PARTICIPANTS REMOVED\n');
    fprintf('================================================\n');

end

%% ============================================================
% 7. CONVERT VARIABLES TO CATEGORICAL
%
% Reference categories:
%
% Condition:
% Silence = reference
%
% Round:
% Round 1 = reference
%% ============================================================

model_data.Subject = ...
    categorical( ...
        model_data.Subject);


model_data.Condition = ...
    categorical( ...
        model_data.Condition_String, ...
        ["silence", "slow", "fast"], ...
        ["Silence", "Slow", "Fast"]);


model_data.Round = ...
    categorical( ...
        model_data.Round_Number, ...
        [1, 2, 3], ...
        ["Round1", "Round2", "Round3"]);


%% Remove original helper columns

model_data.Condition_String = [];

model_data.Round_Number = [];


%% ============================================================
% 8. PRINT DATASET INFORMATION
%% ============================================================

n_trials = ...
    height(model_data);


n_subjects_final = ...
    numel( ...
        categories( ...
        removecats(model_data.Subject)));


fprintf('\n================================================\n');
fprintf('MODEL DATASET\n');
fprintf('================================================\n');


fprintf('\nParticipants = %d\n', ...
    n_subjects_final);


fprintf('Valid trial observations = %d\n', ...
    n_trials);


fprintf('\nObservations by condition:\n');

disp( ...
    groupcounts( ...
        model_data, ...
        'Condition'));


fprintf('\nObservations by round:\n');

disp( ...
    groupcounts( ...
        model_data, ...
        'Round'));


%% ============================================================
% 9. FIT LINEAR MIXED-EFFECTS MODEL
%
% Fixed effects:
%
% Condition
% Round
%
% Random effect:
%
% Participant-specific intercept
%
% This controls for repeated observations from the same person.
%% ============================================================

lme = fitlme( ...
    model_data, ...
    'RT_new ~ Condition + Round + (1|Subject)');


%% ============================================================
% 10. PRINT COMPLETE MODEL
%% ============================================================

fprintf('\n================================================\n');
fprintf('LINEAR MIXED-EFFECTS MODEL\n');
fprintf('================================================\n');


disp(lme);


%% ============================================================
% 11. COEFFICIENT TABLE
%% ============================================================

coefficient_table = ...
    lme.Coefficients;


fprintf('\n================================================\n');
fprintf('MODEL COEFFICIENTS\n');
fprintf('================================================\n');


disp(coefficient_table);


%% ============================================================
% 12. OVERALL TESTS FOR CONDITION AND ORDER
%
% THIS IS VERY IMPORTANT.
%
% The ANOVA table gives:
%
% 1. Overall p-value for Condition
%
%    Does auditory condition explain RT
%    after controlling for Round?
%
% 2. Overall p-value for Round
%
%    Does presentation order explain RT
%    after controlling for Condition?
%% ============================================================

model_effects = ...
    anova(lme);
%% Convert ANOVA output to table for Excel saving

%% ============================================================
% CREATE A REGULAR TABLE FOR EXCEL
%% ============================================================

% The model contains these fixed effects:
effect_names = [ ...
    "(Intercept)"; ...
    "Condition"; ...
    "Round"];

% Number of rows returned by ANOVA
n_effect_rows = size(model_effects, 1);

% Keep only the correct number of names
effect_names = effect_names(1:n_effect_rows);

%% Create regular MATLAB table

model_effects_table = table( ...
    effect_names, ...
    model_effects.FStat, ...
    model_effects.DF1, ...
    model_effects.DF2, ...
    model_effects.pValue);

model_effects_table.Properties.VariableNames = { ...
    'Effect', ...
    'F_Statistic', ...
    'DF1', ...
    'DF2', ...
    'p_Value'};

%% Add significance result

model_effects_table.Statistically_Significant = ...
    model_effects_table.p_Value < 0.05;

fprintf('\n================================================\n');
fprintf('OVERALL MODEL EFFECTS - EXCEL TABLE\n');
fprintf('================================================\n');

disp(model_effects_table);

%% ============================================================
% 13. PRINT SIMPLE INTERPRETATION
%% ============================================================

fprintf('\n================================================\n');
fprintf('HOW TO INTERPRET THE MODEL\n');
fprintf('================================================\n');


fprintf([ ...
    '\nLook at the OVERALL MODEL EFFECTS table.\n\n' ...
    'Condition p-value:\n' ...
    'Tests whether auditory condition is associated with RT\n' ...
    'AFTER statistically controlling for Round.\n\n' ...
    'Round p-value:\n' ...
    'Tests whether first/second/third presentation order\n' ...
    'is associated with RT AFTER controlling for Condition.\n']);


fprintf([ ...
    '\nIn the coefficient table:\n\n' ...
    'Condition_Slow = Slow compared with Silence,\n' ...
    'while holding Round constant.\n\n' ...
    'Condition_Fast = Fast compared with Silence,\n' ...
    'while holding Round constant.\n\n' ...
    'Round_Round2 = Round 2 compared with Round 1,\n' ...
    'while holding Condition constant.\n\n' ...
    'Round_Round3 = Round 3 compared with Round 1,\n' ...
    'while holding Condition constant.\n']);

fprintf('\nIMPORTANT:\n');
fprintf('A negative coefficient means lower log RT,\n');
fprintf('which means FASTER responses.\n\n');
fprintf('A positive coefficient means higher log RT,\n');
fprintf('which means SLOWER responses.\n');


%% ============================================================
% 14. CREATE CLEAR COEFFICIENT RESULTS TABLE
%% ============================================================

clear_results = table( ...
    string(coefficient_table.Name), ...
    coefficient_table.Estimate, ...
    coefficient_table.SE, ...
    coefficient_table.tStat, ...
    coefficient_table.DF, ...
    coefficient_table.pValue);


clear_results.Properties.VariableNames = { ...
    'Predictor', ...
    'Estimate', ...
    'SE', ...
    't_Value', ...
    'DF', ...
    'p_Value'};


clear_results.Statistically_Significant = ...
    clear_results.p_Value < 0.05;


fprintf('\n================================================\n');
fprintf('CLEAR COEFFICIENT RESULTS\n');
fprintf('================================================\n');


disp(clear_results);
%% ============================================================
% 14B. CREATE CLEAR OVERALL EFFECTS TABLE
%
% This table answers:
%
% 1. Is there an overall Condition effect
%    after controlling for Round?
%
% 2. Is there an overall Round effect
%    after controlling for Condition?
%% ============================================================

effect_names_from_model = ...
    string(model_effects.Term);


idx_condition_effect = ...
    find(effect_names_from_model == "Condition");


idx_round_effect = ...
    find(effect_names_from_model == "Round");


overall_effects_clear = table( ...
    ["Condition"; "Round"], ...
    [ ...
        model_effects.FStat(idx_condition_effect); ...
        model_effects.FStat(idx_round_effect) ...
    ], ...
    [ ...
        model_effects.DF1(idx_condition_effect); ...
        model_effects.DF1(idx_round_effect) ...
    ], ...
    [ ...
        model_effects.DF2(idx_condition_effect); ...
        model_effects.DF2(idx_round_effect) ...
    ], ...
    [ ...
        model_effects.pValue(idx_condition_effect); ...
        model_effects.pValue(idx_round_effect) ...
    ]);


overall_effects_clear.Properties.VariableNames = { ...
    'Effect', ...
    'F_Statistic', ...
    'DF1', ...
    'DF2', ...
    'p_Value'};


overall_effects_clear.Statistically_Significant = ...
    overall_effects_clear.p_Value < 0.05;


overall_effects_clear.Question = [ ...
    "Does auditory condition affect RT after controlling for Round?"; ...
    "Does Round affect RT after controlling for Condition?" ...
    ];


fprintf('\n================================================\n');
fprintf('CLEAR OVERALL EFFECTS TABLE\n');
fprintf('================================================\n');


disp(overall_effects_clear);


%% ============================================================
% 14C. PREPARE COEFFICIENT INFORMATION
%% ============================================================

coef_names = ...
    string(coefficient_table.Name);


beta = ...
    coefficient_table.Estimate;


coefficient_covariance = ...
    lme.CoefficientCovariance;


%% Find coefficient positions

idx_slow = ...
    find(coef_names == "Condition_Slow");


idx_fast = ...
    find(coef_names == "Condition_Fast");


idx_round2 = ...
    find(coef_names == "Round_Round2");


idx_round3 = ...
    find(coef_names == "Round_Round3");


%% Use model degrees of freedom

contrast_DF = ...
    coefficient_table.DF(1);


%% ============================================================
% 14D. NEW COMPARISON:
% FAST vs SLOW
%
% Estimate:
% Fast coefficient - Slow coefficient
%% ============================================================

contrast_fast_slow = ...
    zeros(length(beta),1);


contrast_fast_slow(idx_fast) = ...
    1;


contrast_fast_slow(idx_slow) = ...
    -1;


estimate_fast_slow = ...
    contrast_fast_slow' * beta;


SE_fast_slow = ...
    sqrt( ...
        contrast_fast_slow' * ...
        coefficient_covariance * ...
        contrast_fast_slow);


t_fast_slow = ...
    estimate_fast_slow / ...
    SE_fast_slow;


p_fast_slow = ...
    2 * tcdf( ...
        -abs(t_fast_slow), ...
        contrast_DF);


critical_t = ...
    tinv( ...
        0.975, ...
        contrast_DF);


CI_fast_slow_lower = ...
    estimate_fast_slow - ...
    critical_t * SE_fast_slow;


CI_fast_slow_upper = ...
    estimate_fast_slow + ...
    critical_t * SE_fast_slow;


%% ============================================================
% 14E. NEW COMPARISON:
% ROUND 3 vs ROUND 2
%
% Estimate:
% Round 3 coefficient - Round 2 coefficient
%% ============================================================

contrast_round3_round2 = ...
    zeros(length(beta),1);


contrast_round3_round2(idx_round3) = ...
    1;


contrast_round3_round2(idx_round2) = ...
    -1;


estimate_round3_round2 = ...
    contrast_round3_round2' * beta;


SE_round3_round2 = ...
    sqrt( ...
        contrast_round3_round2' * ...
        coefficient_covariance * ...
        contrast_round3_round2);


t_round3_round2 = ...
    estimate_round3_round2 / ...
    SE_round3_round2;


p_round3_round2 = ...
    2 * tcdf( ...
        -abs(t_round3_round2), ...
        contrast_DF);


CI_round3_round2_lower = ...
    estimate_round3_round2 - ...
    critical_t * SE_round3_round2;


CI_round3_round2_upper = ...
    estimate_round3_round2 + ...
    critical_t * SE_round3_round2;


%% ============================================================
% 14F. CREATE ALL CONDITION COMPARISONS
%% ============================================================

condition_comparisons = [ ...
    "Slow vs Silence"; ...
    "Fast vs Silence"; ...
    "Fast vs Slow"];


condition_estimates = [ ...
    coefficient_table.Estimate(idx_slow); ...
    coefficient_table.Estimate(idx_fast); ...
    estimate_fast_slow];


condition_SE = [ ...
    coefficient_table.SE(idx_slow); ...
    coefficient_table.SE(idx_fast); ...
    SE_fast_slow];


condition_t = [ ...
    coefficient_table.tStat(idx_slow); ...
    coefficient_table.tStat(idx_fast); ...
    t_fast_slow];


condition_DF = [ ...
    coefficient_table.DF(idx_slow); ...
    coefficient_table.DF(idx_fast); ...
    contrast_DF];


condition_p_raw = [ ...
    coefficient_table.pValue(idx_slow); ...
    coefficient_table.pValue(idx_fast); ...
    p_fast_slow];


condition_CI_lower = [ ...
    coefficient_table.Lower(idx_slow); ...
    coefficient_table.Lower(idx_fast); ...
    CI_fast_slow_lower];


condition_CI_upper = [ ...
    coefficient_table.Upper(idx_slow); ...
    coefficient_table.Upper(idx_fast); ...
    CI_fast_slow_upper];


%% Bonferroni correction:
% 3 Condition comparisons

condition_p_bonferroni = ...
    min( ...
        condition_p_raw * 3, ...
        1);


condition_significant_after_bonferroni = ...
    condition_p_bonferroni < 0.05;


%% ============================================================
% 14G. CREATE ALL ROUND COMPARISONS
%% ============================================================

round_comparisons = [ ...
    "Round 2 vs Round 1"; ...
    "Round 3 vs Round 1"; ...
    "Round 3 vs Round 2"];


round_estimates = [ ...
    coefficient_table.Estimate(idx_round2); ...
    coefficient_table.Estimate(idx_round3); ...
    estimate_round3_round2];


round_SE = [ ...
    coefficient_table.SE(idx_round2); ...
    coefficient_table.SE(idx_round3); ...
    SE_round3_round2];


round_t = [ ...
    coefficient_table.tStat(idx_round2); ...
    coefficient_table.tStat(idx_round3); ...
    t_round3_round2];


round_DF = [ ...
    coefficient_table.DF(idx_round2); ...
    coefficient_table.DF(idx_round3); ...
    contrast_DF];


round_p_raw = [ ...
    coefficient_table.pValue(idx_round2); ...
    coefficient_table.pValue(idx_round3); ...
    p_round3_round2];


round_CI_lower = [ ...
    coefficient_table.Lower(idx_round2); ...
    coefficient_table.Lower(idx_round3); ...
    CI_round3_round2_lower];


round_CI_upper = [ ...
    coefficient_table.Upper(idx_round2); ...
    coefficient_table.Upper(idx_round3); ...
    CI_round3_round2_upper];


%% Bonferroni correction:
% 3 Round comparisons

round_p_bonferroni = ...
    min( ...
        round_p_raw * 3, ...
        1);


round_significant_after_bonferroni = ...
    round_p_bonferroni < 0.05;


%% ============================================================
% 14H. COMBINE ALL PAIRWISE COMPARISONS
%% ============================================================

comparison_family = [ ...
    repmat("Condition",3,1); ...
    repmat("Round",3,1)];


comparison_name = [ ...
    condition_comparisons; ...
    round_comparisons];


estimate = [ ...
    condition_estimates; ...
    round_estimates];


SE = [ ...
    condition_SE; ...
    round_SE];


t_value = [ ...
    condition_t; ...
    round_t];


DF = [ ...
    condition_DF; ...
    round_DF];


p_value_raw = [ ...
    condition_p_raw; ...
    round_p_raw];


p_value_bonferroni = [ ...
    condition_p_bonferroni; ...
    round_p_bonferroni];


significant_after_bonferroni = [ ...
    condition_significant_after_bonferroni; ...
    round_significant_after_bonferroni];


CI_lower = [ ...
    condition_CI_lower; ...
    round_CI_lower];


CI_upper = [ ...
    condition_CI_upper; ...
    round_CI_upper];


%% ============================================================
% ADD SIMPLE DIRECTION INTERPRETATION
%% ============================================================

direction = ...
    strings(6,1);


for k = 1:6

    if estimate(k) < 0

        direction(k) = ...
            "First item is faster than second";

    elseif estimate(k) > 0

        direction(k) = ...
            "First item is slower than second";

    else

        direction(k) = ...
            "No estimated difference";

    end

end


%% ============================================================
% FINAL PAIRWISE TABLE
%% ============================================================

pairwise_results = table( ...
    comparison_family, ...
    comparison_name, ...
    estimate, ...
    SE, ...
    t_value, ...
    DF, ...
    p_value_raw, ...
    p_value_bonferroni, ...
    significant_after_bonferroni, ...
    CI_lower, ...
    CI_upper, ...
    direction);


pairwise_results.Properties.VariableNames = { ...
    'Family', ...
    'Comparison', ...
    'Estimate', ...
    'SE', ...
    't_Value', ...
    'DF', ...
    'Raw_p', ...
    'Bonferroni_p', ...
    'Significant_After_Bonferroni', ...
    'CI_Lower', ...
    'CI_Upper', ...
    'Direction'};


fprintf('\n================================================\n');
fprintf('ALL PAIRWISE COMPARISONS\n');
fprintf('WITH BONFERRONI CORRECTION\n');
fprintf('================================================\n');


disp(pairwise_results);
%% ============================================================
% 14I. CREATE MODEL-ADJUSTED FIGURES
%
% Figure 1:
% Condition effect after controlling for Round
%
% Figure 2:
% Round effect after controlling for Condition
%
% Error bars = 95% confidence intervals
%% ============================================================


%% Get fixed-effect coefficients

beta = ...
    fixedEffects(lme);


coef_names_for_figures = ...
    string(coefficient_table.Name);


V = ...
    lme.CoefficientCovariance;


%% Find coefficient positions

idx_intercept_fig = ...
    find(coef_names_for_figures == "(Intercept)");


idx_slow_fig = ...
    find(coef_names_for_figures == "Condition_Slow");


idx_fast_fig = ...
    find(coef_names_for_figures == "Condition_Fast");


idx_round2_fig = ...
    find(coef_names_for_figures == "Round_Round2");


idx_round3_fig = ...
    find(coef_names_for_figures == "Round_Round3");


%% ============================================================
% FIGURE 1:
% ADJUSTED CONDITION MEANS
%
% Each condition is averaged equally across:
% Round 1, Round 2, Round 3
%% ============================================================


condition_labels = ...
    ["Silence"; "Slow"; "Fast"];


condition_contrasts = ...
    zeros(3, length(beta));


%% Silence adjusted across all 3 rounds

condition_contrasts(1, idx_intercept_fig) = ...
    1;

condition_contrasts(1, idx_round2_fig) = ...
    1/3;

condition_contrasts(1, idx_round3_fig) = ...
    1/3;


%% Slow adjusted across all 3 rounds

condition_contrasts(2, idx_intercept_fig) = ...
    1;

condition_contrasts(2, idx_slow_fig) = ...
    1;

condition_contrasts(2, idx_round2_fig) = ...
    1/3;

condition_contrasts(2, idx_round3_fig) = ...
    1/3;


%% Fast adjusted across all 3 rounds

condition_contrasts(3, idx_intercept_fig) = ...
    1;

condition_contrasts(3, idx_fast_fig) = ...
    1;

condition_contrasts(3, idx_round2_fig) = ...
    1/3;

condition_contrasts(3, idx_round3_fig) = ...
    1/3;


%% Calculate adjusted means and 95% CI

condition_adjusted_means = ...
    condition_contrasts * beta;


condition_adjusted_SE = ...
    zeros(3,1);


for k = 1:3

    c = ...
        condition_contrasts(k,:)';

    condition_adjusted_SE(k) = ...
        sqrt( ...
            c' * V * c);

end


critical_t_fig = ...
    tinv( ...
        0.975, ...
        coefficient_table.DF(1));


condition_CI = ...
    critical_t_fig * ...
    condition_adjusted_SE;


%% Get Bonferroni p-values

comparison_names_for_figures = ...
    string(pairwise_results.Comparison);


p_slow_silence = ...
    pairwise_results.Bonferroni_p( ...
        comparison_names_for_figures == ...
        "Slow vs Silence");


p_fast_silence = ...
    pairwise_results.Bonferroni_p( ...
        comparison_names_for_figures == ...
        "Fast vs Silence");


p_fast_slow = ...
    pairwise_results.Bonferroni_p( ...
        comparison_names_for_figures == ...
        "Fast vs Slow");


%% ============================================================
% CREATE CONDITION FIGURE
% WITH SIGNIFICANCE BRACKETS
%% ============================================================

figure( ...
    'Color', ...
    'w', ...
    'Name', ...
    'Adjusted Condition Effect');


%% Plot adjusted means with 95% confidence intervals

errorbar( ...
    1:3, ...
    condition_adjusted_means, ...
    condition_CI, ...
    '-o', ...
    'LineWidth', ...
    2, ...
    'MarkerSize', ...
    8);

hold on;


%% ============================================================
% AXIS SETTINGS
%% ============================================================

xlim([0.5 3.5]);

xticks(1:3);

xticklabels( ...
    condition_labels);


xlabel( ...
    'Auditory Condition');


ylabel( ...
    'Adjusted log Reaction Time');

title( ...
    { ...
    'Condition Effect After Controlling for Round'; ...
    'Lower log RT = Faster Responses' ...
    });


grid on;


set(gca, ...
    'Color', ...
    'w', ...
    'XColor', ...
    'k', ...
    'YColor', ...
    'k', ...
    'GridColor', ...
    [0.8 0.8 0.8], ...
    'GridAlpha', ...
    0.5, ...
    'FontSize', ...
    12);


%% ============================================================
% FIND SPACE ABOVE THE GRAPH
%% ============================================================

highest_point = ...
    max( ...
        condition_adjusted_means + ...
        condition_CI);


lowest_point = ...
    min( ...
        condition_adjusted_means - ...
        condition_CI);


graph_range = ...
    highest_point - ...
    lowest_point;


if graph_range == 0

    graph_range = 1;

end


%% Heights for significance brackets

bracket_fast_slow_y = ...
    highest_point + ...
    0.15 * graph_range;


bracket_fast_silence_y = ...
    highest_point + ...
    0.42 * graph_range;


bracket_height = ...
    0.07 * graph_range;


%% Expand Y-axis so brackets are visible

ylim([ ...
    lowest_point - 0.10 * graph_range, ...
    bracket_fast_silence_y + 0.25 * graph_range ...
    ]);


%% ============================================================
% SIGNIFICANCE BRACKET:
% SLOW vs FAST
%% ============================================================

x1 = 2;
x2 = 3;

y = bracket_fast_slow_y;


plot( ...
    [x1 x1 x2 x2], ...
    [ ...
    y, ...
    y + bracket_height, ...
    y + bracket_height, ...
    y ...
    ], ...
    'k-', ...
    'LineWidth', ...
    1.5);


text( ...
    mean([x1 x2]), ...
    y + bracket_height + 0.03 * graph_range, ...
    sprintf( ...
        '**  p = %.4f', ...
        p_fast_slow), ...
    'HorizontalAlignment', ...
    'center', ...
    'FontSize', ...
    11, ...
    'FontWeight', ...
    'bold');


%% ============================================================
% SIGNIFICANCE BRACKET:
% SILENCE vs FAST
%% ============================================================

x1 = 1;
x2 = 3;

y = bracket_fast_silence_y;


plot( ...
    [x1 x1 x2 x2], ...
    [ ...
    y, ...
    y + bracket_height, ...
    y + bracket_height, ...
    y ...
    ], ...
    'k-', ...
    'LineWidth', ...
    1.5);


text( ...
    mean([x1 x2]), ...
    y + bracket_height + 0.03 * graph_range, ...
    sprintf( ...
        '***  p = %.5f', ...
        p_fast_silence), ...
    'HorizontalAlignment', ...
    'center', ...
    'FontSize', ...
    11, ...
    'FontWeight', ...
    'bold');


%% ============================================================
% ADD NOTE ABOUT BONFERRONI CORRECTION
%% ============================================================

text( ...
    0.55, ...
    lowest_point - 0.04 * graph_range, ...
    'Pairwise p-values are Bonferroni-corrected', ...
    'FontSize', ...
    9);


hold off;


%% ============================================================
% SAVE CONDITION FIGURE
%% ============================================================

condition_figure_file = ...
    fullfile( ...
        path, ...
        'Adjusted_Condition_Effect_With_Significance.png');


exportgraphics( ...
    gcf, ...
    condition_figure_file, ...
    'Resolution', ...
    300);


fprintf('\nCondition figure with significance brackets saved here:\n%s\n', ...
    condition_figure_file);


%% ============================================================
% FIGURE 2:
% ADJUSTED ROUND MEANS
%
% Each round is averaged equally across:
% Silence, Slow, Fast
%% ============================================================


round_labels = ...
    ["Round 1"; "Round 2"; "Round 3"];


round_contrasts = ...
    zeros(3, length(beta));


%% Round 1 adjusted across all 3 conditions

round_contrasts(1, idx_intercept_fig) = ...
    1;

round_contrasts(1, idx_slow_fig) = ...
    1/3;

round_contrasts(1, idx_fast_fig) = ...
    1/3;


%% Round 2 adjusted across all 3 conditions

round_contrasts(2, idx_intercept_fig) = ...
    1;

round_contrasts(2, idx_slow_fig) = ...
    1/3;

round_contrasts(2, idx_fast_fig) = ...
    1/3;

round_contrasts(2, idx_round2_fig) = ...
    1;


%% Round 3 adjusted across all 3 conditions

round_contrasts(3, idx_intercept_fig) = ...
    1;

round_contrasts(3, idx_slow_fig) = ...
    1/3;

round_contrasts(3, idx_fast_fig) = ...
    1/3;

round_contrasts(3, idx_round3_fig) = ...
    1;


%% Calculate adjusted means and 95% CI

round_adjusted_means = ...
    round_contrasts * beta;


round_adjusted_SE = ...
    zeros(3,1);


for k = 1:3

    c = ...
        round_contrasts(k,:)';

    round_adjusted_SE(k) = ...
        sqrt( ...
            c' * V * c);

end


round_CI = ...
    critical_t_fig * ...
    round_adjusted_SE;


%% Get Bonferroni p-values

p_round2_round1 = ...
    pairwise_results.Bonferroni_p( ...
        comparison_names_for_figures == ...
        "Round 2 vs Round 1");


p_round3_round1 = ...
    pairwise_results.Bonferroni_p( ...
        comparison_names_for_figures == ...
        "Round 3 vs Round 1");


p_round3_round2 = ...
    pairwise_results.Bonferroni_p( ...
        comparison_names_for_figures == ...
        "Round 3 vs Round 2");


%% Create Round figure

figure( ...
    'Color', ...
    'w', ...
    'Name', ...
    'Adjusted Round Effect');


errorbar( ...
    1:3, ...
    round_adjusted_means, ...
    round_CI, ...
    '-o', ...
    'LineWidth', ...
    2, ...
    'MarkerSize', ...
    8);


xlim([0.5 3.5]);


xticks(1:3);


xticklabels( ...
    round_labels);


xlabel( ...
    'Presentation Round');


ylabel( ...
    'Adjusted Standardized Reaction Time (Z)');


title( ...
    { ...
    'Round Effect After Controlling for Condition'; ...
    'Lower Z = Faster Responses' ...
    });


grid on;


set(gca, ...
    'Color', ...
    'w', ...
    'XColor', ...
    'k', ...
    'YColor', ...
    'k', ...
    'GridColor', ...
    [0.8 0.8 0.8], ...
    'GridAlpha', ...
    0.5, ...
    'FontSize', ...
    12);


%% Add pairwise results as text

round_result_text = sprintf( ...
    [ ...
    'Bonferroni comparisons:\n' ...
    'Round 2 vs Round 1: p = %.4g\n' ...
    'Round 3 vs Round 1: p = %.4g\n' ...
    'Round 3 vs Round 2: p = %.4g' ...
    ], ...
    p_round2_round1, ...
    p_round3_round1, ...
    p_round3_round2);


annotation( ...
    'textbox', ...
    [0.56 0.68 0.31 0.20], ...
    'String', ...
    round_result_text, ...
    'FitBoxToText', ...
    'on', ...
    'BackgroundColor', ...
    'w');


%% Save Round figure

round_figure_file = ...
    fullfile( ...
        path, ...
        'Adjusted_Round_Effect.png');


exportgraphics( ...
    gcf, ...
    round_figure_file, ...
    'Resolution', ...
    300);


fprintf('\n================================================\n');
fprintf('FIGURES CREATED AND SAVED\n');
fprintf('================================================\n');

fprintf('\nCondition figure:\n%s\n', ...
    condition_figure_file);

fprintf('\nRound figure:\n%s\n', ...
    round_figure_file);


%% ============================================================
% 15. SAVE RESULTS TO EXCEL
%% ============================================================

output_excel = ...
    fullfile( ...
        path, ...
        'Mixed_Regression_Condition_Order_RT.xlsx');


%% Save trial-level data

writetable( ...
    model_data, ...
    output_excel, ...
    'Sheet', ...
    'Trial_Level_Data');


%% Save coefficient results

writetable( ...
    clear_results, ...
    output_excel, ...
    'Sheet', ...
    'Coefficients');
writetable( ...
    overall_effects_clear, ...
    output_excel, ...
    'Sheet', ...
    'Overall_Effects_Clear');


writetable( ...
    pairwise_results, ...
    output_excel, ...
    'Sheet', ...
    'Pairwise_Comparisons');


fprintf('\nExcel results saved here:\n%s\n', ...
    output_excel);


%% IMPORTANT:
% model_effects is displayed in the Command Window
% and saved later in the model text file.
%
% We do NOT use writetable for model_effects because
% the MATLAB version returns it in a non-table format.


%% ============================================================
% 16. SAVE MODEL TEXT
%% ============================================================

model_text_file = ...
    fullfile( ...
        path, ...
        'Mixed_Regression_Condition_Order_Model.txt');


diary(model_text_file);


fprintf('\n================================================\n');
fprintf('FINAL MODEL\n');
fprintf('================================================\n');


disp(lme);


fprintf('\n================================================\n');
fprintf('OVERALL EFFECTS\n');
fprintf('================================================\n');


disp(model_effects);


fprintf('\n================================================\n');
fprintf('COEFFICIENTS\n');
fprintf('================================================\n');


disp(coefficient_table);


diary off;


%% ============================================================
% 17. FINISH
%% ============================================================

fprintf('\n================================================\n');
fprintf('DONE\n');
fprintf('================================================\n');


fprintf('\nResults Excel:\n%s\n', ...
    output_excel);


fprintf('\nModel text file:\n%s\n', ...
    model_text_file);